# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('cedula', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('domicilio', models.TextField()),
                ('personaEPN', models.BooleanField()),
            ],
        ),
    ]
